### ISSUE TITLE
This dataset is originated from Big-Bench rather than ART...

### ISSUE THREAD

**Issue by zhimin-z** [CriticBench/CriticBench#1]
![image](https://github.com/CriticBench/CriticBench/assets/8592144/5bad8eee-4566-4859-9c9c-0db31d47f8f5)
Check page `21` in https://arxiv.org/pdf/2402.14809.pdf

**Comment by ZubinGou** [comment]
Hi, thank you for your attention. There might have been some misunderstanding. Table 12 is not about the data source, but rather the "prompt source."

**Comment by zhimin-z** [comment]
> Hi, thank you for your attention. There might have been some misunderstanding. Table 12 is not about the data source, but rather the "prompt source."

But I cannot find relevant information mentioning that `repeat copy` is from `ART`. But I indeed find some illustration that it is from `Big-Bench` as shown in page 4:
![1712809921904](https://github.com/CriticBench/CriticBench/assets/8592144/8b2d06a3-d240-406e-8744-6f2ec3a1ad4f)

@ZubinGou

**Comment by ZubinGou** [comment]
Yeah, the data is sourced from Big-Bench, but the prompt is from ART.

**Comment by zhimin-z** [comment]
> Yeah, the data is sourced from Big-Bench, but the prompt is from ART.

Hmm...this is not mentioned in the arxiv.

**Comment by ZubinGou** [comment]
We have mentioned this: the main text you have presented serves as the citation for the data, and Table 12 indicates the source of the prompt.
