### ISSUE TITLE
Why are these datasets written by the authors?

### ISSUE THREAD

**Issue by zhimin-z** [CriticBench/CriticBench#2]
![image](https://github.com/CriticBench/CriticBench/assets/8592144/51720fdb-b28a-4a69-be77-99dd312adfa2)
Check page 21 at https://arxiv.org/pdf/2402.14809.pdf

**Comment by ZubinGou** [comment]
Hi, thank you for your attention. There might have been some misunderstanding. Table 12 is not about the data source, but rather the "prompt source."

For tabmwp and HumanEval, we did not find commonly used external prompts, so we composed our own prompts to fairly assess the different models.

**Comment by zhimin-z** [comment]
> Hi, thank you for your attention. There might have been some misunderstanding. Table 12 is not about the data source, but rather the "prompt source."
> 
> For tabmwp and HumanEval, we did not find commonly used external prompts, so we composed our own prompts to fairly assess the different models.

Thanks, but `TabMWP`  and `HumanEval` are two benchmark datasets commonly used in academia. How do the prompt source differ in your paper and that dataset in the original ones? I feel very confused on that.

@ZubinGou

**Comment by ZubinGou** [comment]
Thank you for your further query. In our study, we created the few-shot examples for HumanEval and selected samples from the training set as prompts for TabMWP, as neither dataset offers official few-shot prompts. We believe that the variation in prompts should not significantly impact the results.
